/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
    sequence: [
        {
            type: "category",
            label: "Getting Started",
            collapsible: true,
            collapsed: true,
            items: [
                "sequence/get-started/introduction",
                "sequence/get-started/teams",
                "sequence/get-started/ledgers",
                "sequence/get-started/access-control",
                "sequence/get-started/sdks",
                "sequence/get-started/explorer",
                "sequence/get-started/5-minute-guide",
            ],
        },
        {
            type: "category",
            label: "Examples",
            collapsible: true,
            collapsed: true,
            items: [
                "sequence/examples/mobile-wallet",
                "sequence/examples/crypto-exchange",
                "sequence/examples/lending-platform",
                "sequence/examples/ride-sharing",
            ],
        },
        {
            type: "category",
            label: "Ledger Objects",
            collapsible: true,
            collapsed: true,
            items: [
                "sequence/ledger-objects/tokens",
                "sequence/ledger-objects/flavors",
                "sequence/ledger-objects/accounts",
                "sequence/ledger-objects/transactions",
                "sequence/ledger-objects/actions",
                "sequence/ledger-objects/keys",
            ],
        },
        {
            type: "category",
            label: "Ledger Queries",
            collapsible: true,
            collapsed: true,
            items: [
                "sequence/ledger-queries/overview",
                "sequence/ledger-queries/filters",
                "sequence/ledger-queries/pagination",
                "sequence/ledger-queries/list-queries",
                "sequence/ledger-queries/sum-queries",
                "sequence/ledger-queries/feeds",
            ],
        },
        {
            type: "category",
            label: "Reference",
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: "link",
                    label: "Java SDK",
                    href: "https://docs.seq.com/sdk/java/2.2/overview-summary.html",
                },
                {
                    type: "link",
                    label: "Ruby SDK",
                    href: "https://docs.seq.com/sdk/ruby/2.2/index.html",
                },
                {
                    type: "link",
                    label: "Node SDK",
                    href: "https://docs.seq.com/sdk/node/2.2.0/index.html",
                },
                {
                    type: "doc",
                    id: "sequence/reference/pii",
                    label: "PII",
                },
                {
                    type: "doc",
                    id: "sequence/reference/errors",
                    label: "Errors",
                },
            ],
        },
    ],
    cloud: [
        {
            type: "doc",
            id: "cloud/introduction",
            label: "Introduction",
        },
        // Changed by Ozren
        // {
        //     type: "category",
        //     label: "RPC Services",
        //     collapsible: true,
        //     collapsed: true,
        //     items: [
        //         "cloud/rpc-services/rpc-services",
        //         "cloud/rpc-services/standard-api",
        //         {
        //             type: "category",
        //             label: "Premium API",
        //             collapsible: true,
        //             collapsed: true,
        //             items: [
        //                 "cloud/rpc-services/premium-api/premium-api",
        //                 "cloud/rpc-services/premium-api/security",
        //                 "cloud/rpc-services/premium-api/ui-interactions",
        //             ],
        //         },
        //         "cloud/rpc-services/pricing",
        //     ],
        // },
        // {
        //     type: "category",
        //     label: "Node Services",
        //     collapsible: true,
        //     collapsed: true,
        //     items: [
        //         "cloud/node-services/node-services",
        //         "cloud/node-services/architecture",
        //         "cloud/node-services/smart-contract-flows",
        //         "cloud/node-services/payment-methods",
        //         {
        //             type: "category",
        //             label: "Protocol Node",
        //             collapsible: true,
        //             collapsed: true,
        //             items: [
        //                 "cloud/node-services/protocol-node/protocol-node",
        //                 "cloud/node-services/protocol-node/node-staking",
        //             ],
        //         },
        //         "cloud/node-services/enterprise-node",
        //         "cloud/node-services/pricing",
        //     ],
        // },
        {
            type: "category",
            label: "Node Services",
            collapsible: true,
            collapsed: true,
            items: [
                "cloud/node-services/node-services",
                "cloud/node-services/architecture",
                "cloud/node-services/smart-contract-flows",
                "cloud/node-services/enterprise-node",
                "cloud/node-services/pricing",
            ],
        },
        {
            type: "category",
            label: "Supported Chains",
            collapsible: true,
            collapsed: true,
            items: [
                "cloud/supported-chains/arbitrum",
                "cloud/supported-chains/astar",
                "cloud/supported-chains/aurora",
                "cloud/supported-chains/avalanche",
                // "cloud/supported-chains/bsc-network",
                "cloud/supported-chains/bitcoin",
                "cloud/supported-chains/bitcoinCash",
                "cloud/supported-chains/bittorent-chain",
                // "cloud/supported-chains/celo",
                "cloud/supported-chains/cosmos",
                "cloud/supported-chains/cronos",
                "cloud/supported-chains/doge",
                "cloud/supported-chains/eos",
                {
                    type: "category",
                    label: "Ethereum",
                    collapsible: true,
                    collapsed: true,
                    items: [
                        "cloud/supported-chains/ethereum/ethereum",
                        "cloud/supported-chains/ethereum/connect-wallet",
                        "cloud/supported-chains/ethereum/start-making-requests",
                        "cloud/supported-chains/ethereum/basic-project",
                    ],
                },
                "cloud/supported-chains/ethereum-classic",
                // "cloud/supported-chains/fantom",
                "cloud/supported-chains/gnosis",
                "cloud/supported-chains/huobi",
                "cloud/supported-chains/klaytn",
                "cloud/supported-chains/polkadot",
                // "cloud/supported-chains/polygon",
            ],
        },
        {
            type: "category",
            label: "Examples",
            collapsible: true,
            collapsed: true,
            items: ["cloud/examples/web3-gaming"],
        },
        {
            type: "category",
            label: "DAO",
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: "category",
                    label: "Staking",
                    collapsible: true,
                    collapsed: true,
                    items: [
                        "cloud/dao/staking/staking",
                        "cloud/dao/staking/rewards",
                        "cloud/dao/staking/epoch",
                        "cloud/dao/staking/delegates",
                        "cloud/dao/staking/slashing",
                    ],
                },
                {
                    type: "category",
                    label: "Governance",
                    collapsible: true,
                    collapsed: true,
                    items: [
                        "cloud/dao/governance/dao",
                        "cloud/dao/governance/constitution",
                        "cloud/dao/governance/architecture",
                        "cloud/dao/governance/proposal",
                        "cloud/dao/governance/parameters",
                        "cloud/dao/governance/voting",
                        "cloud/dao/governance/treasury",
                    ],
                },
            ],
        },
    ],
};

module.exports = sidebars;
